/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.proyecto_fase2_202010316;

import com.google.gson.Gson;
import java.io.File;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import ABB.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import AVL.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import Albumes.*;
import Matriz.*;
import java.awt.image.BufferedImage;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class moduloUsuario extends javax.swing.JFrame {

    /**
     * Creates new form moduloUsuario
     */
    public moduloUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ver Arbol de Imagenes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Arbol de Capas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver Listado de albumes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ver Capa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Graficar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Graficar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Graficar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Graficar Preorden");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Graficar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton5.setText("Graficar Inorder");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton11.setText("Graficar Postorden");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Generar por imagen");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Generar por capa");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Ver");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton17.setText("Ver");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Ver");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton15.setText("Rotar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Cargar Capas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cargar Imagenes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Cargar Albumes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Cerrar Sesion");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");

        jMenuItem5.setText("Ver");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton14)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton11)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton17)
                                .addGap(95, 95, 95)
                                .addComponent(jButton18)))
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(62, 62, 62)
                                .addComponent(jButton6)
                                .addGap(88, 88, 88)
                                .addComponent(jButton8)
                                .addGap(60, 60, 60)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton6)
                        .addComponent(jButton8)
                        .addComponent(jButton10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(jButton11)
                        .addComponent(jButton5)
                        .addComponent(jButton12)
                        .addComponent(jButton13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton14)
                    .addComponent(jButton17)
                    .addComponent(jButton18)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ARBOL BINARIO DE BUSQUEDA
    public static bst abb = new bst();
    public static bst abbGraphviz = new bst();

    //ARBOL AVL
    public static AVL avl = new AVL();

    //LISTA CIRCULAR DOBLE ENLAZADA
    public static listaAlbum lista_album = new listaAlbum();

    //
    private long id_cliente;

    public long getId_cliente() {
        return id_cliente;
    }

    public void setId_cliente(long id_cliente) {
        this.id_cliente = id_cliente;
    }
    
    public static long idREPORTE;


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            Gson json = new Gson();
            JFileChooser selector = new JFileChooser();
            File file;
            selector.setMultiSelectionEnabled(false);
            FileNameExtensionFilter filtro = new FileNameExtensionFilter(null, "json");
            selector.setFileFilter(filtro);

            if (selector.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {
                file = selector.getSelectedFile();

                Scanner sc = new Scanner(file);
                String data = "";
                while (sc.hasNextLine()) {
                    data += sc.nextLine() + "\n";
                }
                JSONParser parser = new JSONParser();
                Object obj = parser.parse(data);
                JSONArray array = (JSONArray) obj;
                JSONObject jobj;
                for (int i = 0; i < array.size(); i++) {
                    jobj = (JSONObject) array.get(i);
                    System.out.println("-----------------------------------");
                    JSONArray array2 = (JSONArray) jobj.get("pixeles");
                    JSONObject pixeles;

                    String id_capa = String.valueOf(jobj.get("id_capa"));

                    capas capG = new capas(id_cliente, Integer.valueOf(id_capa), 0, 0, "");
                    abbGraphviz.add(capG);

                    for (int j = 0; j < array2.size(); j++) {
                        pixeles = (JSONObject) array2.get(j);

                        //System.out.println("id: "+jobj.get("id_capa"));
                        /*System.out.println("fila: "+pixeles.get("fila"));
                        System.out.println("columna: "+pixeles.get("columna"));
                        System.out.println("color: "+pixeles.get("color"));
                        System.out.println();*/
                        String fila = String.valueOf(pixeles.get("fila"));
                        String columna = String.valueOf(pixeles.get("columna"));

                        capas _capas = new capas(id_cliente, Integer.valueOf(id_capa), Integer.valueOf(fila), Integer.valueOf(columna), String.valueOf(pixeles.get("color")));
                        abb.add(_capas);

                    }

                    System.out.println("-----------------------------------");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ubicacion = "Estructuras\\ABB\\abb_" + id_cliente + ".jpg";
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH));
        jLabel2.setIcon(imgIcon);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        abbGraphviz.graficar(abbGraphviz.root);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            Gson json = new Gson();
            JFileChooser selector = new JFileChooser();
            File file;
            selector.setMultiSelectionEnabled(false);
            FileNameExtensionFilter filtro = new FileNameExtensionFilter(null, "json");
            selector.setFileFilter(filtro);

            if (selector.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {
                file = selector.getSelectedFile();

                Scanner sc = new Scanner(file);
                String data = "";
                while (sc.hasNextLine()) {
                    data += sc.nextLine() + "\n";
                }
                JSONParser parser = new JSONParser();
                Object obj = parser.parse(data);
                JSONArray array = (JSONArray) obj;
                JSONObject jobj;
                for (int i = 0; i < array.size(); i++) {
                    jobj = (JSONObject) array.get(i);
                    System.out.println("-----------------------------------");
                    //System.out.println(jobj.get("id"));

                    String id_imagen = String.valueOf(jobj.get("id"));
                    String capas = String.valueOf(jobj.get("capas"));
                    //System.out.println(capas);
                    imagen img = new imagen(id_cliente, Integer.valueOf(id_imagen), capas);
                    avl.add(img);

                    System.out.println("-----------------------------------");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        avl.graficar(avl.root);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ubicacion = "Estructuras\\AVL\\avl_" + id_cliente + ".jpg";
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH));
        jLabel2.setIcon(imgIcon);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            Gson json = new Gson();
            JFileChooser selector = new JFileChooser();
            File file;
            selector.setMultiSelectionEnabled(false);
            FileNameExtensionFilter filtro = new FileNameExtensionFilter(null, "json");
            selector.setFileFilter(filtro);

            if (selector.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {
                file = selector.getSelectedFile();

                Scanner sc = new Scanner(file);
                String data = "";
                while (sc.hasNextLine()) {
                    data += sc.nextLine() + "\n";
                }
                JSONParser parser = new JSONParser();
                Object obj = parser.parse(data);
                JSONArray array = (JSONArray) obj;
                JSONObject jobj;
                for (int i = 0; i < array.size(); i++) {
                    jobj = (JSONObject) array.get(i);
                    System.out.println("-----------------------------------");
                    //System.out.println(jobj.get("nombre_album"));
                    //System.out.println(jobj.get("imgs"));

                    String nombre_album = String.valueOf(jobj.get("nombre_album"));
                    String imgs = String.valueOf(jobj.get("imgs"));

                    album alb = new album(id_cliente, nombre_album, imgs);
                    lista_album.IngresarAlbum(alb);

                    System.out.println("-----------------------------------");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String ubicacion = "Estructuras\\LC\\lc_" + id_cliente + ".jpg";
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH));
        jLabel2.setIcon(imgIcon);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        lista_album.graficar(id_cliente);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MatrizDispersa matriz = new MatrizDispersa();
        //lista list=new lista();
        //abbGraphviz.imprimirNiveles(abbGraphviz.root,list);
        //list.mostrar();
        //System.out.println(list.obtenerMayor());
        jTextField1.setText("");
        bst.contenido = "";
        abb.preorder(abb.root, matriz, id_cliente);
        abbGraphviz.preordenJtext(abbGraphviz.root, jTextField1, id_cliente);

        //columna fila color
        //matriz.insertar(1, 1,"#FFCC33");
        //matriz.insertar(5, 2,"#FFCC40");
        //matriz.insertar(1, 3,"#FFCC27");
        matriz.graficar(String.valueOf(id_cliente));

    }//GEN-LAST:event_jButton9ActionPerformed

    public static String ubicacionIMG = "";

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String ubicacion = "Estructuras\\PREORDEN\\MDF" + id_cliente + ".jpg";
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH));
        jLabel1.setIcon(imgIcon);
        ubicacionIMG = ubicacion;
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        MatrizDispersa matriz = new MatrizDispersa();
        jTextField1.setText("");
        bst.contenido = "";
        abb.postorder(abb.root, matriz, id_cliente);
        abbGraphviz.postorderJtext(abbGraphviz.root, jTextField1, id_cliente);
        matriz.graficar(String.valueOf(id_cliente));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MatrizDispersa matriz = new MatrizDispersa();
        jTextField1.setText("");
        bst.contenido = "";
        abb.enorder(abb.root, matriz, id_cliente);
        abbGraphviz.enorderJtext(abbGraphviz.root, jTextField1, id_cliente);
        matriz.graficar(String.valueOf(id_cliente));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        File input = new File(ubicacionIMG);
        File output = new File(ubicacionIMG);
        rotate90(input, output, ROTATE_RIGHT);

        String ubicacion = ubicacionIMG;
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH));
        jLabel1.setIcon(imgIcon);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String entradaUsuario = JOptionPane.showInputDialog("Ingrese el id de una imagen:");
        System.out.println("El id ingresado es: " + Integer.valueOf(entradaUsuario));
        //GENERAR IMG POR ID DE IMAGEN
        MatrizDispersa matriz = new MatrizDispersa();
        avl.porIDimagen(avl.root, id_cliente, Integer.valueOf(entradaUsuario), matriz, abb);
        matriz.graficarPorIMG(String.valueOf(id_cliente));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String ubicacion = "Estructuras\\PORIMAGEN\\MDF" + id_cliente + ".jpg";
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH));
        jLabel1.setIcon(imgIcon);
        ubicacionIMG = ubicacion;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String ubicacion = "Estructuras\\PORCAPA\\MDF" + id_cliente + ".jpg";
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH));
        jLabel1.setIcon(imgIcon);
        ubicacionIMG = ubicacion;
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        MatrizDispersa matriz = new MatrizDispersa();
        String entradaUsuario = JOptionPane.showInputDialog("Ingrese el numero total de capas a evaluar:");
        for (int i = 0; i < Integer.valueOf(entradaUsuario); i++) {
            String numeroCapa = JOptionPane.showInputDialog("Ingrese el id de la capa:");
            abb.bstIngresoCapa(abb.root, matriz, id_cliente, Integer.valueOf(numeroCapa));
        }
        matriz.graficarPorCapa(String.valueOf(id_cliente));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        MatrizDispersa matriz = new MatrizDispersa();
        String entradaUsuario = JOptionPane.showInputDialog("Ingrese el numero de capa:");
        abb.bstIngresoCapa(abb.root, matriz, id_cliente, Integer.valueOf(entradaUsuario));
        matriz.graficoLogico(String.valueOf(id_cliente));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String ubicacion = "Estructuras\\CAPALOGICO\\MD" + id_cliente + ".jpg";
        Image imagen = new ImageIcon(ubicacion).getImage();
        ImageIcon imgIcon = new ImageIcon(imagen.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH));
        jLabel2.setIcon(imgIcon);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        idREPORTE=id_cliente;
        reportesUsuario mu = new reportesUsuario();
        mu.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    public static final int ROTATE_LEFT = 1;
    public static final int ROTATE_RIGHT = -1;

    public void rotate90(File input, File output, int direction) {
        try {
            ImageInputStream iis = ImageIO.createImageInputStream(input);
            Iterator<ImageReader> iterartor = ImageIO.getImageReaders(iis);
            ImageReader reader = iterartor.next();
            String format = reader.getFormatName();

            BufferedImage image = ImageIO.read(iis);
            int width = image.getWidth();
            int height = image.getHeight();

            BufferedImage rotated = new BufferedImage(height, width, image.getType());

            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    switch (direction) {
                        case ROTATE_LEFT:
                            rotated.setRGB(y, (width - 1) - x, image.getRGB(x, y));
                            break;
                        case ROTATE_RIGHT:
                            rotated.setRGB((height - 1) - y, x, image.getRGB(x, y));
                            break;
                    }
                }
            }

            ImageIO.write(rotated, format, output);

        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moduloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moduloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moduloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moduloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moduloUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
